---
- name: Apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install pip
  apt:
    name: "{{ xkeysnail_dependencies }}"
  vars:
    xkeysnail_dependencies:
      - python3
      - python3-pip
      - x11-xserver-utils

- name: Install xkeysnail
  pip:
    name: "xkeysnail"
    version: "{{ xkeysnail_version }}"
    executable: /usr/bin/pip3
  register: xkeysnail_install_result

- name: Set xkeysnail executable as /usr/bin/xkeysnail
  set_fact:
    xkeysnail_executable: /usr/local/bin/xkeysnail

