---
- name: Install xkeysnail
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Ensure that input and uinput group exists
  group:
    name: "{{ item }}"
  with_items:
    - "{{ xkeysnail_groups }}"

- name: Add user to group
  user:
    name: "{{ ansible_user }}"
    groups: "{{ xkeysnail_groups }}"
    append: yes
  become: yes

- name: Ensure that config directory exists
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  with_items:
    - '{{ xkeysnail_config_home }}'
    - '{{ xkeysnail_config_dir }}'
    - '{{ xkeysnail_service_dir }}'

- name: Download config.py from given gist url
  get_url:
    url: "{{ xkeysnail_config_gist_url }}/raw/config.py"
    dest: "{{ xkeysnail_config_dir }}/"
  register: xkeysnail_config_download
  until: xkeysnail_config_download is succeeded
  retries: 3
  delay: 5
  when: xkeysnail_config_gist_url is defined
  notify:
    - restart_xkeysnail

- name: Copy config.py
  copy:
    src: 'files/config.py'
    dest: '{{ xkeysnail_config_dir }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  when: xkeysnail_config_gist_url is not defined
  notify:
    - restart_xkeysnail

- name: Allow user to access /dev/input/*
  lineinfile:
    path: '{{ item.path }}'
    line: '{{ item.line }}'
    create: yes
  with_items:
    - "{{ xkeysnail_udev_rules }}"
  become: yes

- name: Add rules for apparmor
  template:
    src: usr.local.bin.xkeysnail.j2
    dest: /etc/apparmor.d/usr.local.bin.xkeysnail
    owner: root
    group: root
    mode: 0644
  become: yes
  when: xkeysnail_apparmor_enabled | bool
  notify:
    - reload_apparmor_for_xkeysnail

- name: Place service file
  template:
    src: xkeysnail.service.j2
    dest: "{{ xkeysnail_service_dir }}/xkeysnail.service"
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0600
  notify:
    - reload_xkeysnail

- name: Enable xkeysnail service
  systemd:
    name: xkeysnail
    enabled: yes
    state: started
    scope: user
