- name: Add IUS repository
  yum:
    name: 'https://centos7.iuscommunity.org/ius-release.rpm'

- name: Install dependencies
  yum:
    name: "{{ xkeysnail_dependencies }}"
    update_cache: yes
  vars:
    xkeysnail_dependencies:
      - python36u
      - python36u-pip
      - python36u-setuptools
      - python36u-devel
      - "kernel-headers-{{ ansible_kernel }}"
      - gcc

- name: Install xkeysnail
  pip:
    name: "xkeysnail"
    version: "{{ xkeysnail_version }}"
    executable: /usr/bin/pip3.6
  register: xkeysnail_install_result
  vars:
    ansible_python_interpreter: /usr/bin/python3.6

- name: Set xkeysnail executable as /usr/bin/xkeysnail
  set_fact:
    xkeysnail_executable: /usr/bin/xkeysnail
