---
- name: Reload xkeysnail daemon
  systemd:
    name: xkeysnail
    state: restarted
    daemon_reload: yes
    scope: user
  listen: reload_xkeysnail

- name: Restart xkeysnail daemon
  systemd:
    name: xkeysnail
    state: restarted
    scope: user
  listen: restart_xkeysnail
