---
- name: Reload xkeysnail daemon
  systemd:
    name: xkeysnail
    state: restarted
    daemon_reload: yes
    scope: user
  listen: reload_xkeysnail

- name: Restart xkeysnail daemon
  systemd:
    name: xkeysnail
    state: restarted
    scope: user
  listen: restart_xkeysnail

- name: Reload apparmor rule
  shell: apparmor_parser -r /etc/apparmor.d/usr.local.bin.xkeysnail
  listen: reload_apparmor_for_xkeysnail
  become: yes
